---
title: "Examples"
author: "Robin J. Evans"
date: "24/05/2022"
output: html_document
vignette: >
  %\VignetteIndexEntry{Examples}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  echo = TRUE
)
```

```{r load, message=FALSE}
library(survivl)
library(dplyr)
```

## Two Examples

```{r params1}
formulas <- list(C ~ 1,
                 Z ~ X_l1 + C,
                 X ~ Z_l0 + C,
                 Y ~ X_l0 + C,
                 cop ~ 1)
family <- list(5,1,5,3,1)
link <- list("logit", "identity", "logit", "inverse")
pars <- list(C = list(beta=0),
             Z = list(beta = c(-1/2,1/2,0.25), phi=0.5),
             X = list(beta = c(0,1/2,1/10)),
             Y = list(beta = c(0.05,0.5,0.05), phi=1),
             cop = list(beta=0.8472979))  # gives correlation 0.4
```

## Simulating Data

```{r sim_dat1}
set.seed(123)
m <- 1e3
dat <- data.frame(C=rbinom(m,size=1,prob=0.5))
dat$Z_0 <- rnorm(m, dat$C/4 - 1/2)
dat$X_0 <- rbinom(m, size=1, prob=0.5)

dat2 <- msm_samp(dat=dat, T=5, formulas=formulas, family=family, pars=pars, link=link)
datl <- surv_to_long(dat2)
n <- 1e4
dat <- msm_samp(n, T=20, formulas=formulas, family=family, pars=pars, link=link)
datl <- surv_to_long(dat)
```

```{r plot_dat1, message=FALSE}
library(ggfortify)
library(survival)
survplot <- survfit(Surv(t, t_stop, Y) ~ C, data=datl)
autoplot(survplot)
```

```{r glms1}
modX <- glm(X ~ Z + C, family=binomial, data=datl)
prop_score <- predict(modX, type = "response")
datl <- datl %>% mutate(wt=datl$X/prop_score + (1-datl$X)/(1-prop_score))
```

```{r glms2a}
library(survey)
mod_w <- svyglm(I(1-Y) ~ X + C, family=binomial(link=log), start=c(-0.01,-.5,-.05),
                design=svydesign(ids=~1, data=datl, weights=rep(1,nrow(datl))))
mod_c <- svyglm(I(1-Y) ~ X + C, family=binomial(link=log), start=c(-0.01,-.5,-.05),
                design=svydesign(ids=~1, data=datl, weights=datl$wt))
summary(mod_w)
summary(mod_c)
```

```{r tabs, eval=FALSE, echo=FALSE}
tab_w <- cbind(pars$Y$beta, -mod_w$coef, summary(mod_w)$coef[,-c(1,3)])
tab_w[,4] <- pt(abs((tab_w[,2]-tab_w[,1])/tab_w[,3]), df=n-4, lower.tail = FALSE)
tab_c <- cbind(pars$Y$beta, -mod_c$coef, summary(mod_c)$coef[,-c(1,3)])
tab_c[,4] <- pt(abs((tab_c[,2]-tab_c[,1])/tab_c[,3]), df=n-4, lower.tail = FALSE)
library(kableExtra)
kableExtra::kbl(tab_w, digits = c(2,3,5,2), booktabs=TRUE, format="latex")  %>%  
  kableExtra::add_header_above(c("Coef","Truth","Est.", "Std. Err.", "p-value"))
kableExtra::kbl(tab_c, digits = c(2,3,5,2), booktabs=TRUE, format="latex")  %>%  
  kableExtra::add_header_above(c("Coef","Truth","Est.", "Std. Err.", "p-value"))
```

### Example 2 (doesn't work)

We assume:
 - $C$ is a Bernoulli r.v. with parameter $1/2$;
 - $Z_t$ is a normal random variable with mean $C - 1/2 + X_{t-1}$;
 - $X_t$ is a Gamma random variable with log mean $Z_t/3 + C/3$;
 - $Y_t$ is an underlying exponential distribution with rate $X_t + C$;
 - the copula between $Y_t$ and $Z_t$ is Gaussian with fixed correlation.

```{r params2}
formulas <- list(C ~ 1,
                 Z ~ X_l1 + C,
                 X ~ Z_l0 + C,
                 Y ~ X_l0 + C,
                 cop ~ 1)
family <- list(5,1,3,3,1)
link <- list("logit", "identity", "log", "inverse")
pars <- list(C = list(beta=0),
             Z = list(beta = c(-1/2,1/4,1), phi=0.5),
             X = list(beta = c(0,1/4,1/20), phi=0.25),
             Y = list(beta = c(0,0.2,0.05), phi=1),
             cop = list(beta=1))
```

### Simulating Data

```{r sim_dat2}
set.seed(123)
dat <- msm_samp(1e4, T=20, formulas=formulas, family=family, pars=pars, link=link)
datl <- surv_to_long(dat)
```

```{r plot_dat2, message=FALSE}
library(ggfortify)
library(survival)
survplot <- survfit(Surv(t, t_stop, Y) ~ C, data=datl)
autoplot(survplot)
```

```{r glms2}
modX <- glm(X ~ Z + C, family=Gamma(link=log), data=datl)
prop_score <- predict(modX, type = "link")
datl <- datl %>% mutate(wt=dgamma(datl$X,shape=1/pars$X$phi, rate=1/(sum(pars$X$beta*c(1,mean(datl$Z), mean(datl$C)))*pars$X$phi))/dgamma(datl$X, shape=1/pars$X$phi, rate=1/(pars$X$phi*exp(prop_score))))
# datl$wt[is.na(datl$wt)] <- 0
```

```{r glms2b}
library(survey)
mod_w <- svyglm(I(1-Y) ~ X + C, family=binomial(link=log), start=c(0,-.2,-.05),
                design=svydesign(ids=~1, data=datl, weights=rep(1,nrow(datl))))
mod_c <- svyglm(I(1-Y) ~ X + C, family=binomial(link=log), start=c(0,-.2,-.05),
                design=svydesign(ids=~1, data=datl, weights=datl$wt))
summary(mod_w)
summary(mod_c)
```
